branches:
  except:
  - gh-pages
sudo: false
language: node_js
cache:
  directories:
  - node_modules
node_js:
- '9'
- '10'
matrix:
  fast_finish: true
before_install:
- npm set progress=false ; npm install -g grunt-cli
notifications:
  slack:
    secure: CCyhDHQ0id5hC8WkumD4SzZU1PS46oqfqcW5DX7Sxfvx+6On0b8Tq3bWbtB2fP9gg7RXhAM31F7n5wXZnw9Meri8gbxP3o/O3vl1sVwvcEVvzbNOCQZK+MJ3dYdAI4cOr6+WHERpAsqaAWZ4Ed2iT9rMrOAK2QY1wPvDsbJMIgQ=
