branches:
  except:
  - gh-pages
sudo: false
dist: trusty
language: node_js
cache:
  directories:
  - node_modules
node_js:
- '8'
- '10'
matrix:
  fast_finish: true
before_install:
- npm set progress=false ; npm install -g grunt-cli
notifications:
  slack:
    secure: baBP4Hn2PzB5Bb+O+Xgykwz26o4QFlhBBf7fwlbnYCgXGDQ/SOfRZMv6Epm+81C9DTQzniVHnjDf0/waqFsW6SRPzq3eUcoca3Hc9G0BR6GMINHn7a/2zQtiQ9xqnmvEY3Hez5nloEi6H/811cB2vMWGdPb+is6iwQkCnZYN4Mk=
