branches:
  except:
  - gh-pages
sudo: false
language: node_js
node_js:
- '0.10'
- '0.11'
- '0.12'
- '4.3'
- '5.7'
before_script:
- npm install -g npm@latest && npm install -g grunt-cli
notifications:
  slack:
    secure: b1k8lo3qvcHi+QCTUwun1fX9+fbnZQoQ77XQ1tS3NoynSJ1K3TMDYNs08uzjQLSvPo877mVDdAPUor8mi0VMM0zukOwlDevxv1ht0nh+MiM21a82S0wqzxzgO5KYbnlFRPW1FzjKZ+Awv7w2sFpZpGkrxPBSM0HEjsFTffarF0E=
