branches:
  except:
  - gh-pages
sudo: false
dist: trusty
language: node_js
cache:
  directories:
  - node_modules
node_js:
- '8'
- '10'
matrix:
  fast_finish: true
before_install:
- npm set progress=false ; npm install -g grunt-cli
notifications:
  slack:
    secure: ZetlLp6ldyjRW30UyHMtE2iIcg5O6lYTXbAZ+WeLYiBIGZn2GlAL44n0hjucOscOW3Q34ODb9AY6sgyVSGcwLr15PGXaRo9SsSYvScQvb3wmqW2Qjunw9OQeRedEW4CLpdxzCTdaWSBhiQUF2bFkihXVwN6KvHtX0Y16c1TBRYw=
