branches:
  except:
  - gh-pages
os: linux
git:
  depth: 12
  submodules: false
language: node_js
cache:
  directories:
  - node_modules
node_js:
- '14'
- '15'
- '16'
- '18'
matrix:
  fast_finish: true
before_install:
- npm set progress=false ; npm install -g grunt-cli
notifications:
  slack:
    secure: T8k1Tud6lT1GYhmCGYYeQFBK+4BaHKO7jLjeLeQmEOrt+9Wl44lYo2+twwrHdnwyGJ0m+/QUwKr2/etd06HxFYTwkhUAF8JAi7Ubnet9EKSc8L0mcHXRco64Ity1OAFUyMgKOr7Uev3OAdzPLH5/DzWUZ/az5bLirdedsQz8r67hVxcFbxDE5CD97NWrTBdtwlyFuByYVDgjlkyRNhtKTnGpI6pszC0IkxDVjBv7G865Wo7gxVAWYZRKE2yoUnHpa8Fd/YGNwO6D7XXaDnivLG3l9Q5powRgxSJm2Nf2ZGXBc5Gov/RY2QUoVgHJsNbHprgvwBDxnT8Gg4D4FzFnfAe6/NNTLRvqihWBLJC841cB5YxNeGnW0Z7z8phJdgMFOvGc0fAiRjqgVS3rFq5plxAfyXNw64NTaizSUGPn7PJ+lVIlHUKEgm0+uBIuTpVG1ofyHMkE2lRzglySzNrKohfNEmFSxh3LtVjJ4UYydi9xixFdVBfpn7X+gJdfLFHTgy//VOYzlCCzuxC3aWZaSum3+dKPoB1f7s0A/v2VUzQW2eQTTAJfe2IuDKdbE5s/MBzoKaZ6EN3+5YBho9sc4bvKJH1Bls1ibY8HeL0Oife4pMd9lErwstOeZhl/TjCcTUG5VLAg7eKPr6mUTwtWXmYyVlpitsFGToQx2CjIVPI=
